source: ./src
destination: ./site
permalink: /:categories/:title
paginate: 5
sections: [about, blog, folio, lab, contact]
#exclude: [about, folio, blog, contact]
env: 
  local: http://localhost:1337
  staging: http://staging.destroytoday.com
  production: http://destroytoday.com
feed: http://feeds.feedburner.com/destroytoday