source: ./src
destination: ./site
permalink: /:categories/:title
paginate: 10
sections: [about, blog, folio, lab, contact]
env: 
  local: http://localhost:1337
  staging: http://staging.destroytoday.com
  production: http://destroytoday.com